name: Report

on:
  workflow_call:
  workflow_dispatch:

jobs:
  Report:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v6

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: 'maven'

      - name: Download Allure results
        uses: actions/download-artifact@v4
        with:
          name: allure-results
          path: target/allure-results

      - name: Generate Allure report
        run: mvn allure:report

      - name: Upload Allure HTML report
        uses: actions/upload-artifact@v4
        with:
          name: allure-report
          path: target/site/allure-maven-plugin
          retention-days: 5