name: SauceDemo CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    uses: ./.github/workflows/build.yml
  test:
    needs: build
    uses: ./.github/workflows/test.yml
  report:
    needs: test
    if: always()
    uses: ./.github/workflows/report.yml